name: Merge master into nightly

on:
  push:
    branches: [ master ]

jobs:
  merge-to-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # all branches and tags
      - name: Merge
        run: |
          git checkout nightly
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git merge master
      - name: Push
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin nightly
